apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "service.fullname" . }}
  labels: {{ include "service.labels" . | nindent 4 }}
  {{- if or .Values.namespace .Release.Namespace }}
  namespace: {{ or .Values.namespace .Release.Namespace }}
  {{- end}}
  annotations:
  {{ include "service.annotations" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.secret }}
  {{ $key | upper }}: {{ $value | toString | b64enc | quote }}
  {{- end }}
